version: '3'

spring:
  application:
    name: tollrate-service-ui

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'

resilience4j:
  timelimiter:
    instances:
      tollrate-cb.timeout-duration: 4s
  circuitbreaker:
    instance:
      tollrate-cb:
      register-health-indicator: true
      sliding-window-size: 3







server:
  port: 8081
