FROM openjdk:11-jre-slim
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]




version: '3'

services:
  app-instance-1:
    build:
      context: .
    ports:
      - "8081:8080"

  app-instance-2:
    build:
      context: .
    ports:
      - "8082:8080"

docker-compose build
docker-compose up



-- container name service

FROM openjdk:11-jre-slim
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]

docker build -t your-image-name:latest .


version: '3'

services:
  app-instance-1:
    image: your-image-name:latest
    container_name: app-instance-1
    ports:
      - "8081:8080"

  app-instance-2:
    image: your-image-name:latest
    container_name: app-instance-2
    ports:
      - "8082:8080"

docker-compose up
