version: '3'

spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DB_URL}
    username: ${SPRING_DB_USERNAME}
    password: ${SPRING_DB_PASSWORD}
  jpa:
    show-sql: true

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
