#name: CI/CD Pipeline
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: '11'
#
#      - name: Build with Maven
#        run: mvn clean install
#
#  deploy:
#    runs-on: ubuntu-latest
#
#    needs: build
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Build Docker image
#        run: docker build -t your-docker-image:latest .
#
#      - name: Push Docker image to registry
#        run: |
#          echo ${{secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#          docker push your-docker-image:latest
#
#      - name: Deploy to production
#        run: docker-compose -f docker-compose-prod.yml up --build -d
#
